from __future__ import annotations

import csv
import json
from argparse import ArgumentParser
from pathlib import Path

import cv2


def build_parser() -> ArgumentParser:
    parser = ArgumentParser(description="Extract labeled single-word clips from concatenated sentence videos.")
    parser.add_argument(
        "--manifest-csv",
        default=r"c:\Users\qqq02\Desktop\99_docs_analysis\metadata\sentence_video_manifest_50.csv",
        help="Sentence video manifest generated by build_sentence_video_dataset.py",
    )
    parser.add_argument(
        "--output-root",
        default=r"c:\Users\qqq02\Desktop\99_docs_analysis\datasets\sentences\00_sentence_word_segments_50",
        help="Output folder containing per-word extracted clips.",
    )
    parser.add_argument(
        "--output-manifest-csv",
        default=r"c:\Users\qqq02\Desktop\99_docs_analysis\metadata\sentence_word_segments_manifest_50.csv",
        help="Output CSV summarizing extracted clips.",
    )
    parser.add_argument(
        "--gap-frames",
        type=int,
        default=2,
        help="Gap frames inserted between words in the sentence builder.",
    )
    parser.add_argument(
        "--context-frames",
        type=int,
        default=1,
        help="Extra leading/trailing frames kept around each word segment.",
    )
    return parser


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_all_frames(video_path: Path) -> tuple[list, float, tuple[int, int]]:
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"Unable to open sentence video: {video_path}")
    fps = cap.get(cv2.CAP_PROP_FPS)
    if not fps or fps <= 1:
        fps = 25.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    frames = []
    while True:
        ok, frame = cap.read()
        if not ok:
            break
        frames.append(frame)
    cap.release()
    if not frames:
        raise RuntimeError(f"No frames found in sentence video: {video_path}")
    return frames, fps, (width, height)


def write_clip(frames: list, output_path: Path, fps: float, size: tuple[int, int]) -> None:
    ensure_dir(output_path.parent)
    writer = cv2.VideoWriter(str(output_path), cv2.VideoWriter_fourcc(*"mp4v"), float(fps), size)
    if not writer.isOpened():
        raise RuntimeError(f"Unable to open writer for clip: {output_path}")
    for frame in frames:
        writer.write(frame)
    writer.release()


def main() -> None:
    args = build_parser().parse_args()
    manifest_path = Path(args.manifest_csv)
    output_root = Path(args.output_root)
    output_manifest = Path(args.output_manifest_csv)
    ensure_dir(output_root)
    ensure_dir(output_manifest.parent)

    rows_out: list[dict] = []
    with manifest_path.open("r", encoding="utf-8-sig", newline="") as handle:
        manifest_rows = list(csv.DictReader(handle))

    for row in manifest_rows:
        sentence_id = row["sentence_id"]
        sentence_video = Path(row["output_video"])
        tokens = json.loads(row["tokens_json"])
        source_counts = [int(value) for value in json.loads(row["source_frame_counts_json"])]
        frames, fps, size = read_all_frames(sentence_video)

        cursor = 0
        for token_index, (token, source_count) in enumerate(zip(tokens, source_counts), start=1):
            start = max(0, cursor - args.context_frames)
            end = min(len(frames), cursor + source_count + args.context_frames)
            clip_frames = frames[start:end]
            clip_name = f"{sentence_id}_w{token_index:02d}_{token}.mp4"
            clip_path = output_root / token / clip_name
            write_clip(clip_frames, clip_path, fps, size)

            rows_out.append(
                {
                    "sentence_id": sentence_id,
                    "word_index": token_index,
                    "token": token,
                    "clip_path": str(clip_path.resolve()),
                    "source_sentence_video": str(sentence_video.resolve()),
                    "frame_start": start,
                    "frame_end_exclusive": end,
                    "core_frame_start": cursor,
                    "core_frame_end_exclusive": cursor + source_count,
                    "fps": round(fps, 2),
                    "frame_count": len(clip_frames),
                }
            )
            cursor += source_count
            if token_index < len(tokens):
                cursor += args.gap_frames

    with output_manifest.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "sentence_id",
                "word_index",
                "token",
                "clip_path",
                "source_sentence_video",
                "frame_start",
                "frame_end_exclusive",
                "core_frame_start",
                "core_frame_end_exclusive",
                "fps",
                "frame_count",
            ],
        )
        writer.writeheader()
        writer.writerows(rows_out)

    print(f"Sentence videos: {len(manifest_rows)}")
    print(f"Extracted word clips: {len(rows_out)}")
    print(f"Output root: {output_root}")
    print(f"Output manifest: {output_manifest}")


if __name__ == "__main__":
    main()
